[build]
  # Este comando pode ser diferente se você não usa Create React App
  command = "npm run build"
  publish = "build"

[[redirects]]
  # Esta regra é opcional, mas boa para ter URLs de API mais limpas (ex: /api/generate-copy)
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200